const OWNER_UUID = process.env.VPN_UUID;

// The old Railway-container-fronted-by-Cloudflare setup (VPS in Eurobyte's Amsterdam network,
// CF_HOST/VPN_HOST below) turned out to be throttled specifically on Russian mobile carriers
// (Tele2 confirmed) at the DPI level - WebSocket-over-Cloudflare completed its handshake and even
// carried some traffic, but real page loads stalled or never completed. Direct VLESS+REALITY to
// that same VPS had the same problem even over Wi-Fi with no carrier involved, and even when
// masquerading as a real, unrelated site (microsoft.com, etc) - pointing at that VPS's hosting
// network itself being throttled for tunnel-shaped traffic, not a fixable protocol/SNI detail.
//
// What actually works on Tele2 (verified live, both Wi-Fi and LTE): VLESS+TCP+REALITY hosted on
// H1cloud VPS nodes, connected to BY HOSTNAME (not raw IP - so the address a censor sees actually
// resolves to the IP it's connecting to, unlike a REALITY server reached by bare IP while
// pretending to be an unrelated domain), on a non-443 high port (RKN's DPI reportedly does full
// inspection mainly on :443 to save resources), masquerading as x5.ru (a well-known, high-traffic
// *Russian* site - blending in as domestic traffic rather than an oddly-hosted foreign brand).
// These specific inbounds were set up manually through each H1cloud VPS's 3x-ui panel (H1cloud's
// own built-in VLESS panel API produces servers with the exact same visible parameters that do
// NOT work on Tele2, so something about 3x-ui's/its Xray-core build specifically matters here -
// not just the SNI/port/hostname choices, which is why every H1_SERVERS entry below has to be a
// real, individually-provisioned 3x-ui client rather than something generated by this service).
//
// There's no API access yet to provision a fresh per-subscriber client on these 3x-ui panels (the
// panel frontend is a bespoke SPA whose backend routes resist scripted login), so every
// subscriber currently shares the one client UUID that was manually created per H1cloud server.
// That's fine for VPN access itself, just not for per-subscriber revocation on these 3 servers.
let H1_SERVERS = [];
try {
  H1_SERVERS = JSON.parse(process.env.VPN_H1_SERVERS || '[]');
} catch {
  H1_SERVERS = [];
}

const CF_HOST = process.env.CF_HOST || '';
const CF_WS_PATH = process.env.CF_WS_PATH || '/xr-8f3a2b1c';
const CF_XHTTP_PATH = process.env.CF_XHTTP_PATH || '/xh-4d9c1e7a';
const VPN_HOST = process.env.VPN_HOST || '';
const VPN_PORT = process.env.VPN_PORT || '443';
const REALITY_PUBLIC_KEY = process.env.VPN_REALITY_PUBLIC_KEY || '';
const REALITY_SHORT_ID = process.env.VPN_REALITY_SHORT_ID || '';
const REALITY_SNI = process.env.VPN_REALITY_SNI || 'www.python.org';

/** Round-robins the given location name across the configured H1cloud 3x-ui servers, so the many
 * displayed "countries" spread evenly across the few servers that actually work on Tele2. */
function h1Link(index, remark) {
  const server = H1_SERVERS[index % H1_SERVERS.length];
  const r = encodeURIComponent(remark);
  // No "flow" param here on purpose: the manually-provisioned 3x-ui clients this points at
  // weren't set up with xtls-rprx-vision, and adding it to the link without the server side
  // matching breaks the handshake instead of just being ignored.
  const params = new URLSearchParams({
    type: 'tcp',
    encryption: 'none',
    security: 'reality',
    pbk: server.pbk,
    fp: 'firefox',
    sni: 'x5.ru',
    sid: server.sid,
    spx: server.spx,
  });
  return `vless://${server.uuid}@${server.host}:${server.port}?${params.toString()}#${r}`;
}

function vlessLink(uuid, remark, transport = 'ws') {
  const r = encodeURIComponent(remark);
  if (CF_HOST) {
    // xhttp rides plain HTTP/2 request/response semantics rather than a raw WebSocket upgrade,
    // which blends in with ordinary browser traffic better - some mobile carriers' DPI flags and
    // resets long-lived WS upgrades specifically, so xhttp is offered as the LTE-bypass transport.
    if (transport === 'xhttp') {
      const params = new URLSearchParams({
        security: 'tls',
        encryption: 'none',
        type: 'xhttp',
        path: CF_XHTTP_PATH,
        host: CF_HOST,
        sni: CF_HOST,
        mode: 'auto',
      });
      return `vless://${uuid}@${CF_HOST}:443?${params.toString()}#${r}`;
    }
    const params = new URLSearchParams({
      security: 'tls',
      encryption: 'none',
      type: 'ws',
      path: CF_WS_PATH,
      host: CF_HOST,
      sni: CF_HOST,
    });
    return `vless://${uuid}@${CF_HOST}:443?${params.toString()}#${r}`;
  }
  const params = new URLSearchParams({
    security: 'reality',
    encryption: 'none',
    pbk: REALITY_PUBLIC_KEY,
    fp: 'chrome',
    sni: REALITY_SNI,
    sid: REALITY_SHORT_ID,
    type: 'tcp',
    flow: 'xtls-rprx-vision',
  });
  return `vless://${uuid}@${VPN_HOST}:${VPN_PORT}?${params.toString()}#${r}`;
}

const LOCATIONS = [
  '\u{1F1EE}\u{1F1F3} India', '\u{1F1EE}\u{1F1E9} Indonesia', '\u{1F1F8}\u{1F1EC} Singapore',
  '\u{1F1F9}\u{1F1ED} Thailand', '\u{1F1F0}\u{1F1ED} Cambodia', '\u{1F1ED}\u{1F1F0} Hong Kong',
  '\u{1F1F9}\u{1F1FC} Taiwan', '\u{1F1F9}\u{1F1F7} Turkey', '\u{1F1E8}\u{1F1FE} Cyprus',
  '\u{1F1FA}\u{1F1F8} US #1', '\u{1F1FA}\u{1F1F8} US #2 Dallas', '\u{1F1EF}\u{1F1F5} Japan',
  '\u{1F1E8}\u{1F1E6} Canada', '\u{1F1E6}\u{1F1FA} Australia', '\u{1F1F2}\u{1F1FE} Malaysia',
  '\u{1F1F3}\u{1F1F1} Netherlands #1', '\u{1F1F8}\u{1F1EA} Sweden', '\u{1F1E6}\u{1F1F1} Albania',
  '\u{1F1F3}\u{1F1F4} Norway', '\u{1F1EA}\u{1F1F8} Spain', '\u{1F1F1}\u{1F1FB} Latvia',
  '\u{1F1EB}\u{1F1EE} Finland #2', '\u{1F1E8}\u{1F1FF} Czech',
];
const LTE_BYPASS = Array.from({ length: 8 }, (_, i) => `LTE • Обход Б/С #${i + 1} - Все Операторы`);
const WHITELIST = Array.from({ length: 3 }, (_, i) => `Белый список • Обход блокировок #${i + 1}`);

function formatExpiry(expiresAt) {
  if (!expiresAt) return null;
  const d = new Date(expiresAt.replace(' ', 'T') + 'Z');
  if (Number.isNaN(d.getTime())) return null;
  return d.toLocaleDateString('ru-RU', { day: '2-digit', month: '2-digit', year: 'numeric' });
}

/** `expiresAt` (SQLite `datetime('now')` string, UTC) is embedded as a read-only info entry
 * at the top of the location list so it shows inside Happ/INCY's own server picker. */
function subscriptionBase64(uuid, expiresAt) {
  const names = [...LOCATIONS, ...LTE_BYPASS, ...WHITELIST];
  // H1cloud's 3x-ui REALITY servers are the only transport confirmed working on Russian mobile
  // carriers (see the comment above H1_SERVERS) - route every displayed location through them,
  // round-robin, whenever at least one is configured. CF_HOST/VPN_HOST stay as the fallback path
  // (Wi-Fi-only, via vlessLink) for as long as VPN_H1_SERVERS is unset.
  const entries = H1_SERVERS.length
    ? names.map((n, i) => h1Link(i, n))
    : names.map((n) => vlessLink(uuid, n));
  const expiryLabel = formatExpiry(expiresAt);
  if (expiryLabel) {
    entries.unshift(H1_SERVERS.length ? h1Link(0, `⏳ Подписка активна до ${expiryLabel}`) : vlessLink(uuid, `⏳ Подписка активна до ${expiryLabel}`));
  }
  return Buffer.from(entries.join('\n'), 'utf8').toString('base64');
}

const COUNTRY_COUNT = new Set(
  LOCATIONS.map((l) => l.replace(/#\d+/, '').replace(/\s+(Dallas)?$/, '').trim())
).size;

module.exports = {
  vlessLink,
  subscriptionBase64,
  formatExpiry,
  OWNER_UUID,
  COUNTRY_COUNT,
};
